name: quick_listener
description: A Dart package to make setting up streams and stream subscriptions a lot simpler.
version: 0.0.1
repository: https://github.com/Calebh101/quick_listener

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

  example:
    path: example
